image: jamesdesq/homepage_builder:v0.1

pipelines:
  branches:
    master:
      - step:
          name: Zip it up
          script:
            - apk update && apk add bash && apk add git
            - apk add zip
            - zip -r application.zip . 
      - step:
          name: Put it out
          script:
            - ls -al
            - zip -r application.zip . 
            - pipe: atlassian/aws-elasticbeanstalk-deploy:0.5.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: "eu-west-2"
                APPLICATION_NAME: "sitemap-app"
                ENVIRONMENT_NAME: 'sitemap-app-dev'
                ZIP_FILE: "application.zip"