image: jamesdesq/homepage_builder:v0.1

pipelines:
  branches:
    master:
      - step:
          name: Build and deploy
          script:
            - apk update && apk add bash && apk add git
            - apk add python3
            - python --version
            - apk add --update py3-pip
            - pip install awsebcli --ignore-installed setuptools --upgrade
            - eb --version
