image: atlassian/default-image:2

pipelines:
  branches:
    master:
      - step:
          name: Zip it up
          script:
            - zip -r application.zip .
          artifacts: 
            - application.zip 
      - step:
          name: Put it out
          script:
            - pipe: atlassian/aws-elasticbeanstalk-deploy:0.5.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: "eu-west-2"
                APPLICATION_NAME: "sitemap-app"
                ENVIRONMENT_NAME: 'sitemap-app-dev'
                ZIP_FILE: "application.zip"