image: jamesdesq/homepage_builder:v0.1

pipelines:
  branches:
    master:
      - step:
          name: Build and deploy
          script:
            - apk update && apk add bash && apk add git
            - apk add build-essential zlib1g-dev libssl-dev libncurses-dev libffi-dev libsqlite3-dev libreadline-dev libbz2-de
            - apk add python3
            - python --version
            - apk add --update py3-pip
            - pip3 install awsebcli --ignore-installed setuptools --upgrade
            - eb --version
